### ISSUE TITLE
Support installing packages with bun/deno insteaf of node

### ISSUE THREAD

**Issue by lucax88x** [williamboman/mason.nvim#1035]
### I've searched open issues for similar requests

Yes

### Is your feature request related to a problem? Please describe.

node is pretty slow in general, inspired by this [post](https://www.reddit.com/r/neovim/comments/11bpzmk/lsp_typescript_and_tailwind_with_bun_major) would be cool if we could install same packages using bun instead of node.

Would that be possible?

### Describe the solution you'd like

Install packages with bun/deno instead of node.

### Describe potential alternatives you've considered

installing packages manually, losing mason potential

### Additional context

https://www.reddit.com/r/neovim/comments/11bpzmk/lsp_typescript_and_tailwind_with_bun_major/

**Comment by eckon** [comment]
Hey, I tried it myself on a bigger typescript project and can say that the bun version is way faster than the normal node version (at least with lsp via `typescript-language-server`).

In my example project the normal  `typescript-language-server` via node will take around 5s to be ready to use, the bun version is instant. Completion also seems to be quicker, but that could be just imagination and placebo effect.

@mattiasbonte I did not do much research how this all works, but I would expect `tsc`, `tsserver/typescripts-language-server` to be written in js/ts. And afterwards being run via a runtime (e.g. node/bun).
I would be surprised if it is compiled to an executable (but there are probably repos that do this for performance reason), but if I am wrong, please correct me :).

Some small examples against them being binaries:
- after installing `tsc` it just points to a js file, which will require another js file 
  - ![image](https://user-images.githubusercontent.com/40291209/221414877-60113662-de24-4f8a-a99b-3d708cac60eb.png)
  - I am guessing this links to this js file in the typescript repo https://raw.githubusercontent.com/microsoft/TypeScript/main/lib/tsc.js
- after installing `typescript-language-server` it just points to a js file, which will be run via `node`
  - ![image](https://user-images.githubusercontent.com/40291209/221415718-0277407e-0255-454a-866f-b2e7105934b2.png)

One question that I am not sure about is, how bun handles these scripts, as both use `node` in their shebang, but that I will leave open for now.


Generally speaking, I currently disabled `tsserver` via mason, as it otherwise will install it automatically (and ignore my local bun version). And will try out the local bun version. If mason would support custom installer or even allows for bun to be used for this installation that would be nice.

I also looked into the way to add new packages via mason-registry but could not find an easy way to overwrite the `tsserver` config or inject into it to update the installation process. So if anyone else has a quickfix that allows this, without a PR, that would also be appreciated :).

**Comment by mattiasbonte** [comment]
Hey @eckon, sorry for deleting my original question didn't see you had wrote a reply to me! I also looked into it and saw it points to js files and not executables. Thanks for your response.

What I notice though.. is that when I look at my btop. Both language servers are running inside node, and node bun. 
<img width="686" alt="image" src="https://user-images.githubusercontent.com/65280774/221417002-c2650e99-c139-4a9b-9c6e-b034d0bbd96f.png">

**Comment by eckon** [comment]
@mattiasbonte no problem. And yes, while writing the reply I looked further into it, and was also confused how it should work (see end of my last reply):

> [...] how bun handles these scripts, as both use node in their shebang [...]

Both scripts seem to be still using node at the end. So no obvious use of bun here. And thinking about it a bit more - that makes sense, bun and node are different things. So we can not expect that everything that can be run via node, just magically works inside bun. So bun might just install the same "executable" as node and runs it the same as node. (unless someone rewrites tsserver with bun in mind)

I am just surprised how I (and seemingly others - in the reddit thread) saw performance increases. If the resulting "exe" is still being used via node (unless the step of not using mason was the problem - but currently this seems to be also not an issue on my machine).

Now when I try to compare node vs "bun" scripts, I dont see any differences, the initial (local) autocompletion seems to be instant now (maybe someone added caching or I never noticed it). The request of external resources (jump to definition, type definition, hover) is the same as it always was before (kinda slow). I need to wait until tsserver is setup completely (around 5s) and then everything works as expected, but no difference between installing via npm/node, bun or masonInstall (npm/node).

Maybe others can show that it really results in a performance improvement, and how to reproduce it. Guess for now ill revert my config back to the normal way of just using node via mason and leave this ticket.

If installing via bun still requires node to run it in the end, then I dont see a reason for this feature (unless people dont want to use npm i guess)

**Comment by williamboman** [comment]
Hey, also see my answer [here](https://github.com/williamboman/mason.nvim/discussions/1031#discussioncomment-5110814). Using Bun to install packages will not be considered because of the reasons mentioned in the link. As for the claimed perceived performance boosts, I'm a bit skeptical because from what I can tell from their post they've not explicitly done anything to actually use `bun` as the runtime.

As other people mentioned here, executables installed via Bun will simply use the shebang included in the executable file (normally `#!/usr/bin/env node`). So far, Bun just ends up being a different package installer than npm. As for using Bun as the actual runtime, I believe the idiomatic way of launching executables is via `bun run --bun <executable>`. This will shim the `node` executable to use `bun` under the hood (as for how far they've come in terms of feature parity with Node.js I don't know, so use at own risk).

**Comment by MagicDuck** [comment]
Just wanted to add another data point that I've also tried it but did not work out.
According to the bun docs here, https://bun.sh/docs/cli/bunx#shebangs, you can get around the node shebang by running
```
bunx --bun typescript-language-server --stdio
```
But when I do that, it works in the cli, but fails inside nvim with the following error according to :LspLog
```
[ERROR][2023-02-26 21:35:36] .../vim/lsp/rpc.lua:733	"rpc"	"bunx"	"stderr"	'\n\nwarn: Invalid original column value\n/Users/stephanbadragan/.bun/install/global/node_modules/typescript-language-server/lib/cli.mjs:1:0 4035022381 |       if (ev === "data") {\n2382 |         state.readableListening = this.listenerCount("readable") > 0;\n2383 |         if (state.flowing !== false) {\n2384 |           __DEBUG__ && debug("in flowing mode!", this.__id);\n2385 | \n2386 |           this.resume();\n             ^\nEINVAL: Invalid argument\nsyscall: "fstat"\n  errno: -22\n\n      at node:stream:2386:10\n      at onData (/Users/stephanbadragan/.bun/install/global/node_modules/typescript-language-server/lib/cli.mjs:2747:11)\n      at listen (/Users/stephanbadragan/.bun/install/global/node_modules/typescript-language-server/lib/cli.mjs:2449:20)\n      at /Users/stephanbadragan/.bun/install/global/node_modules/typescript-language-server/lib/cli.mjs:2210:31\n      at /Users/stephanbadragan/.bun/install/global/node_modules/typescript-language-server/lib/cli.mjs:11777:141\nerror: "typescript-language-server" exited with code 1 (SIGHUP)\n'
```
So it seems like it sadly doesn't work for now...

**Comment by jqhr** [comment]
Bun has release 1.0.For now, it is currently compatible with node.js.
More than that, it can omit node_modules, greatly saving disk space.
See this picture.
![tfugj4n3l6ez](https://github.com/williamboman/mason.nvim/assets/23305067/37bba8ee-5449-4fb5-8eac-890a68ba1dd6)
I thought we can support bun. OR give some way (such as plugin) for use to develop to support it.
@williamboman
