### ISSUE TITLE
Offline Install

### ISSUE THREAD

**Issue by patrickjcasey** [williamboman/mason.nvim#1321]
I am trying to bring my neovim setup to an offline environment, but I am having issues getting my LSPs to work correctly. Currently I am copying over `~/.config/nvim` and `~/.local/share/nvim` to my offline machine. All of my plugins are working except for my LSPs. I can see all of the symlink'd LSPs in `~/.local/share/nvim/mason/bin`, but Mason does not recognize that they are already installed. Is there a way to force Mason to work in `offline` mode and just use the LSP versions on the system and not attempt to update them?

**Comment by williamboman** [comment]
So one thing to be aware of is that the symlinks that Mason creates will have absolute paths, so if you want something that works just by copying the directory over you need to ensure that `~/.local/share/nvim/mason` expands to the exact same, absolute, path on both systems. This is not by design but more a result of a limited/non-existent std lib for working with fs paths in Lua, see #1156.

> Mason does not recognize that they are already installed.

What do you mean by this? When you do `:Mason` nothing shows up as installed?

**Comment by patrickjcasey** [comment]
I updated all of those symlinks to be absolute paths and it worked. Thanks for being so responsive! If anyone else has this issue, I fixed it by updating all of the symlinks in ~/.local/share/nvim/mason/bin. 

```
cd ~/.local/share/nvim/mason/bin
unlink rust-analyzer
ln -s `readlink -f ../packages/rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu` rust-analyzer
```
Repeat for all desired LSPs

**Comment by panboo0106** [comment]
thanks for 

> I updated all of those symlinks to be absolute paths and it worked. Thanks for being so responsive! If anyone else has this issue, I fixed it by updating all of the symlinks in ~/.local/share/nvim/mason/bin.
> 
> ```
> cd ~/.local/share/nvim/mason/bin
> unlink rust-analyzer
> ln -s `readlink -f ../packages/rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu` rust-analyzer
> ```
> 
> Repeat for all desired LSPs

thanks for the work
