### ISSUE TITLE
[Request] add dart server

### ISSUE THREAD

**Issue by JSilva6** [williamboman/mason.nvim#136]
Please add a dart server in order to help us, flutter devs <3

**Comment by williamboman** [comment]
Hello! The Dart language server is bundled with the Dart runtime executable itself. Most likely you've already got Dart installed on your system, in which case you're good to go! I wouldn't really be opposed to including an installer for Dart, but at this point it's borderline out of scope. Before opening up for installing compilers & runtimes I'd like to explore whether project-local installations would make sense in mason (essentially so that you could toggle different versions of a package in different working directories).
