### ISSUE TITLE
[Request] add volar language server

### ISSUE THREAD

**Issue by dagadbm** [williamboman/mason.nvim#137]
### Is your feature request related to a problem? Please describe.

Missing volar language server for vue 3.

### Describe the solution you'd like

Support for volar language server

**Comment by williamboman** [comment]
Hello! The volar language server already exist under the name `vue-language-server`. I decided to go with that name instead of `volar` because per my understanding Volar is the name of a family of Vue tooling, and not just an LSP server, so I figured it'd be a bit misleading. But that was maybe a bad take on my part?

**Comment by wobsoriano** [comment]
Hey! Awesome work on this.

Is there a way to enable [Volar Takeover mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode)?
