### ISSUE TITLE
rust-analyzer RustEmitIr and RustEmitAsm fail (RustExpandMacro works)

### ISSUE THREAD

**Issue by EdmundsEcho** [williamboman/mason.nvim#1395]
### I've searched open issues for similar requests

- [X] Yes

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

I can run the `RustExpandMacro` with success.  This suggests the rust-analyzer is able to find the packages to which my project depends.  However, `RustExpandIr` and `RustEmitAsm` both fail.  They are not able to resolve the dependencies.  

```fish
error[E0432]: unresolved import `valuable`
 --> main.rs:1:5
  |
1 | use valuable::{NamedValues, Valuable, Value, Visit};
  |     ^^^^^^^^ maybe a missing crate `valuable`?
  |
  = help: consider adding `extern crate valuable` to use the `valuable` crate
```

To further qualify the scope of the issue, I can get the requested outputs running `cargo rustc -- --emit=llvm-ir`.

### Expected behavior

It should compile and otherwise emit the `Asm` or `LLVM-Ir`.

### Steps to reproduce

1. `:RustEmitIr` (neovim command window)

### Affected packages

rust-analyzer

### Neovim version (>= 0.7)

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Darwin Edmunds-MacBook-Pro.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64 arm64 MacBookPro18,3 Darwin

### Healthcheck

```Text
==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- WARNING mason.nvim version v1.5.0
  - ADVICE:
    - The latest version of mason.nvim is: v1.6.0
- OK PATH: prepend
- OK Providers: 
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-07-05-last-lagena` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- OK wget: `GNU Wget 1.21.4 built on darwin22.4.0.`
- OK curl: `curl 7.87.0 (x86_64-apple-darwin22.0) libcurl/7.87.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0`
- OK gzip: `Apple gzip 403.100.6`
- OK tar: `tar (GNU tar) 1.34`
- OK bash: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- OK Ruby: `ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin22]`
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- OK cargo: `cargo 1.72.0-nightly (0c14026aa 2023-06-14)`
- OK Go: `go version go1.18 darwin/arm64`
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code 1 and signal 0. The operation couldn’t be completed. Unable to locate a Java Runtime.
      Please visit http://www.java.com for information on installing Java.
      
- OK node: `v20.3.1`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- WARNING java: not available
  - ADVICE:
    - spawn: java failed with exit code 1 and signal 0. The operation couldn’t be completed. Unable to locate a Java Runtime.
      Please visit http://www.java.com for information on installing Java.
      
- OK python: `Python 3.11.4`
- OK luarocks: `/opt/homebrew/bin/luarocks 3.8.0`
- OK RubyGem: `3.0.3.1`
- OK npm: `8.1.0`
- OK pip: `pip 23.0.1 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)`
- OK python venv: `Ok`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Wed Jul  5 12:42:23 2023.
  Install and authenticate via gh-cli to increase rate limit.
```

**Comment by williamboman** [comment]
Hello! Does this also happen if you install rust-analyzer via `rustup component add rust-analyzer` (uninstalling from Mason may help ensure it's running rustup's binary)?

**Comment by EdmundsEcho** [comment]
It does indeed happen with either one.

**Comment by williamboman** [comment]
Ok! I don't see this being a Mason issue then. The `:RustEmitIr` command comes from https://github.com/rust-lang/rust.vim, which I don't believe uses the LSP at all.

**Comment by EdmundsEcho** [comment]
@williamboman I agree with your conclusion based on what I presented.

I have since done some digging into "where all my rust-analyzers" are.  What I mean by that is that there are a few places where I might have installed rust-analyzer.  

To confirm that the rust-analyzer version aligns with the rustc version, I did some more digging.

I cleared out the version I installed using `rustup` and `brew`.  When I take a look at the version in the `$HOME/.local/share/nvim/mason/bin`, I can't quickly determine if the version is aligned with the `rustc` version for the project.  In general, how does mason align the versions based on the toolchain used on a specific version? (or is that not an issue)

**Comment by EdmundsEcho** [comment]
Thank you for your replies.

> Do you mean in your shell? Sure! This plugin already does this when you call require("mason").setup().

I have the following in my setup.  The mason installed apps (e.g., rust-analyzer), was not available outside of neovim.   To level-set, I use tmux and open new shells outside of the neovim context.

```lua
require("mason").setup({
    ui = {
        icons = {
            package_installed = "✓",
            package_pending = "➜",
            package_uninstalled = "o",
        },
    },
})
require("mason-lspconfig").setup()
```
Is it possible that by including the following in my setup, I have overwritten the default configuration that would have added `mason` to my `PATH`?  

(To avoid this, I presumed the default values are set outside of the setup and used when the setup does not specify a value).

**Comment by williamboman** [comment]
That will indeed only override the settings you've provided and use the defaults for the rest. Note that this will only set up the `PATH` inside Neovim. If you open nvim and for example do `:!which rust-analyzer` you should see Mason's installation show up if it's installed.

To access executables outside of Neovim, for example in a shell, you'll have to manually add Mason's bin path to your `PATH`, for example in your `~/.bashrc`, `-/.zshrc` etc. (again if you use Neovim's `:term` or other shell features you won't have to do this because the shell inherits Neovim's environment)

**Comment by EdmundsEcho** [comment]
> HOME/.local/share/nvim/lsp_servers was the installation directory for the old nvim-lsp-installer plugin, so this directory can be safely removed.

Ah, the `nvim-lsp-installer` is the now the deprecated version of this, `mason` plugin... Anything that I installed using `:LspInstall` can be found in the `lsp_servers` directory.  I can delete that.  Good.

### Only to confirm:
Are there other directories that I can clear out?  Are there directories that are shared between the two (`mason` and the deprecated plugin)?

### When is `LspInstall` deleted? (it's not)
I deleted the deprecated version of the plugin (including `PlugClean` to delete it's directories).  This should have removed the `LspInstall` and related functions from my neovim; deprecated, "instead use `MasonInstall`".

However, that is not the case.

* does `mason` define these `Lsp*` functions?
* does `mason-lspconfig` define these `Lsp*` functions?

**Comment by williamboman** [comment]
> Are there other directories that I can clear out? Are there directories that are shared between the two (mason and the deprecated plugin)?

That's the most important one to clean up in terms of preserving disk space. The only other file should be a log file, which I think should be inside `~/.local/share/nvim` or `~/.cache/nvim`.

> does mason define these Lsp* functions?
does mason-lspconfig define these Lsp* functions?

The `:LspInstall` command comes from mason-lspconfig. This auxiliary plugin fills in the gaps between Mason and nvim-lsp-installer to make it easier to migrate, it also contains some convenience stuff (auto-setup of installed servers).

**Comment by williamboman** [comment]
> I can install various apps using `mason`. But there is no way to add user-specified settings for those apps. Yes?

Mason _only_ installs packages for you, it doesn't "integrate" these in any way in Neovim (other than making executables and other files available in the editor). For example to use LSP servers you have multiple options:

- use the builtin LSP client via `:h vim.lsp.start()` directly inside a `FileType` autocmd (or `ftplugin/rust.lua`)
- use `nvim-lspconfig` to access a default server configuration and logic for starting and attaching servers to buffers. Apart from a rather big set of default server configurations, `nvim-lspconfig` is just a pretty thin wrapper around `vim.lsp.start()`.
- use a 3rd party LSP client, such as https://github.com/prabirshrestha/vim-lsp, https://github.com/autozimu/LanguageClient-neovim, or perhaps even https://github.com/neoclide/coc.nvim
- manually launch a LSP server in a `:term` buffer and manually write JSON-RPC spec-compliant requests via stdin and read the JSON responses (don't 🤣)

The same applies to other tooling such as formatters and linters, where you can for example:
- integrate these so that diagnostics appear inside the editor via for example null-ls.nvim
- manually call these in a `:term` buffer or `:!stylua %`

The way you provide the desired configuration depends on which approach you take. Many packages automatically detect project-local configuration by looking for a configuration file, for example `stylua.toml`.

> If so, the motivation for `mason-lspconfig` is to add user-specified `setup`s when the user wants to customize for the installed apps. Yes?

The motivation behind `mason-lspconfig` is basically:
1) provide mappings between Mason package names and lspconfig server configuration names (e.g. `lua-language-server -> lua_ls`)
2) provide facilities to automatically set up servers installed in Mason, avoiding the need to manually do this for each server you want to use
3) provide extra, necessary, server configuration not included in nvim-lspconfig (only applies to a few select servers)
4) provide convenience APIs such as `:LspInstall` to select a server that is associated with the current buffer's filetype or `:LspInstall lua_ls` to be able to install a server by providing the nvim-lspconfig name

**Comment by EdmundsEcho** [comment]
Very helpful.  Thank you.

Having worked with the `lua` version of the setup for over a year now, I have experienced the "sequencing" issues required to manage operating the setup as expected.

Clearly one major pain-point is the "where and when" to call `setup`.  To get the apps in question to work within neovim,  my ideal workflow would be something like the following:

1. Load the packages with `mason`; each will operate with default settings.
2. To override the default, have a single, or series of files that just contains the definition of the lua table for `setup`

The only "need to know" outside of this, is whether to place the custom configurations before or after mason setup.

To run the lsps using :term and otherwise, I would assume that I'm running whatever the path points to, and that any custom settings would need to be read-in from $HOME (or whatever each lsp documents for how it looks for configuration files).
