### ISSUE TITLE
Convert selene to use pre-built binary

### ISSUE THREAD

**Issue by WhoIsSethDaniel** [williamboman/mason.nvim#173]
### Is your feature request related to a problem? Please describe.

Convert the `selene` package to install the pre-compiled binary available on github. Should be similar to how `stylua` was converted from rust-compiled to pre-built binary.

https://github.com/Kampfkarren/selene/releases

 

### Describe the solution you'd like

`selene` installation uses the pre-built binary on platforms where a provided binary is available.

### Additional context

Installing via pre-built binary is much faster.

**Comment by WhoIsSethDaniel** [comment]
I looked at doing this and I had a working config, but with some caveats:
1. no pre-built binary for macos-aarch64. Not certain if that's a problem.
2. I could not get the installed `selene` to be set to +x. I should have looked deeper but I can't ATM. The installed `selene` binary is installed w/o executable permission.

**Comment by williamboman** [comment]
> * no pre-built binary for macos-aarch64. Not certain if that's a problem.

Generally macOS binaries tend to run well on the ARM chips, thanks to Rosetta and universal mac binaries.

> 2\. I could not get the installed `selene` to be set to +x. I should have looked deeper but I can't ATM. The installed `selene` binary is installed w/o executable permission.

Hm, I've been meaning to implement both an interactive installation mode where you'll be able to step through installations, as well as a flag that will keep installation artifacts upon failure (instead of always removing them). Both will hopefully help debugging things (and shouldn't be that difficult to implement).
