### ISSUE TITLE
Automating mason install process

### ISSUE THREAD

**Issue by s1n7ax** [williamboman/mason.nvim#467]
### I've searched open issues for similar requests

- [X] Yes

### Is your feature request related to a problem? Please describe.

I have a docker image with neovim installed I'm using to edit files. When building the image, I can automate the packer installation and tree-sitter installation. However, in mason, it's hard to do because there is no way to find out when the installation is done.

I'm using following command to run a new instance each time I want to use Neovim and remove the container when I'm leaving. This way I can mount different directories to different instances on the fly.

```bash
docker run -it --rm -v /home/s1n7ax/Workspace/kt-kubernetes/02_microservice/result-app:/app s1n7ax/neovim:1.0 /bin/bash
```

Following shows how I automate the install process for packer & tree-sitter when building the docker image.
https://github.com/s1n7ax/dotnvim/blob/38bbfa9e7ced507def005bad5a3c8f15e67dae82/Dockerfile#L60

This runs `PackerSync` and on `PackerComplete` event, it runs `quitall` to quit.

```
RUN nvim \
    --headless \
    -c 'autocmd User PackerComplete quitall' \
    -c 'silent PackerSync'
```

This runs `TSInstallSync all` and runs `quitall` once it's done.

```
RUN nvim \
    --headless \
    -c 'set cmdheight=50' \
    -c 'silent TSInstallSync all' \
    -c 'sleep 20' \
    -c 'qall'
```

### Describe the solution you'd like

Solution 1:
* Fire an event when mason is done installing all the packages

Solution 2:
* Add synchronous install method

**Comment by williamboman** [comment]
`:MasonInstall` runs in blocking/synchronous mode when no UIs are attached (i.e. `nvim --headless`). Is this not working for you?

**Comment by samjwill** [comment]
@williamboman Hello! I have a question that I figure I'll ask here since it seems relevant to the parent issue.

I was wondering if there was a synchronous command that would `:MasonInstall` the packages that I've already defined in my mason-lspconfig `ensure_installed` table that gets passed to the setup function, without needing to explicitly pass the packages along manually. Basically, the goal is to be able to have the option to install the packages headlessly through a bash script (something along the lines of `nvim --headless -c "MasonInstallAll" -c "quitall"`), or have them installed on initial Neovim startup.

Re-defining the same packages in both my headless install script _and_ in my Neovim init files via the `ensure_installed` table works, though I'm kind of a fan of the DRY principle. Would you have any suggestions on what the best approach to handling this might be?

Thanks!

**Comment by williamboman** [comment]
You could try something like

```lua
local ensure_installed = { "rust_analyzer", "sumneko_lua" }
mason_lspconfig.setup { ensure_installed = ensure_installed }

vim.api.nvim_create_user_command("MasonInstallAll", function ()
  vim.cmd("MasonInstall " .. table.concat(ensure_installed, " "))
end, {})
```

**Comment by samjwill** [comment]
Ahh, that's clever. Thanks!

**Comment by siduck** [comment]
@williamboman  I have a custom function that captures mason pkg names from user's lspconfig, conform etc. but the :install() is async. Is it possible to make it sync? I want it sync so i could use it in headless mode or something like a on_finish hook when mason's done downloading everything

```lua

M.install_all = function()
  vim.cmd "Mason"

  local mr = require "mason-registry"

  mr.refresh(function()
    for _, tool in ipairs(M.get_pkgs()) do
      local p = mr.get_package(tool)

      if not p:is_installed() then
        p:install()
      end
    end
  end)
end
```
