### ISSUE TITLE
Change popup window color

### ISSUE THREAD

**Issue by duarm** [williamboman/mason.nvim#635]
### I've searched open issues for similar requests

Yes

### Is your feature request related to a problem? Please describe.

The window has the same color as my background, how can I change the color of the :Mason window only? is there any highlight group for it? couldn't find on the documentation nor any issue about it.

### Describe the solution you'd like

A highlight group to change the :Mason window background color

**Comment by williamboman** [comment]
This was already possible by modifying the `NormalFloat` highlight (like `:highlight NormalFloat guibg=red`). In #636 I added a "highlight alias" `(`:h winhighlight`) specific to Mason called `MasonNormal`, which can be used to change the background of the Mason window specifically. Due to the lazy nature of the UI (highlight groups are only defined upon window creation) you'll have to leverage `:h autocmd` to override it:

```vim
autocmd FileType mason highlight MasonNormal guibg=red
```

or in slightly more verbose Lua:

```lua
vim.api.nvim_create_autocmd("FileType", {
    pattern = "mason",
    callback = function ()
        vim.api.nvim_set_hl(0, "MasonNormal", { bg = "red" })
    end
})

```

**Comment by shauryagoel** [comment]
Hi, is there a way to change border color in a similar way (using highlight groups)?
