### ISSUE TITLE
Clarification for initial setup instructions

### ISSUE THREAD

**Issue by drk-mtr** [williamboman/mason.nvim#663]
### I've searched open issues for similar requests

Yes

### Is your feature request related to a problem? Please describe.

Thanks for the brilliant tool! I struggled to understand how to get started.

### Describe the solution you'd like

The setup instructions state the following:

```
The only thing needed to get started with mason.nvim is to make sure to call
the `setup()` function:

    require("mason").setup()
```

It doesn't state where this should be called from. I believe the answer is "the vimrc configuration file".

When I add this to the vimrc configuration file, it doesn't work. I need to use the following instead, but I'm not sure whether I'm doing this the right way. Is it worth stating these things in the instructions?

```
lua << EOF
    require("mason").setup()
EOF
```

**Comment by williamboman** [comment]
Hey! Ah I see. So that snippet can be called from anywhere really. Some might want to lazily set up the plugin upon a certain `:h autocmd` event, others might want to put it in a location in `:h startup` where Neovim executes it for you, others might want to couple it with hooks provided by their plugin manager, others might want to do it somewhere within their initialization script. 

It's a very common pattern for Lua-based Neovim plugins to provide a `.setup()` function that needs to be explicitly called by the user. I'd like to think that this pattern is so common that I don't think this plugin would be a good place to explain it.

> When I add this to the vimrc configuration file, it doesn't work. I need to use the following instead, but I'm not sure whether I'm doing this the right way. Is it worth stating these things in the instructions?

So it seems like your using vimscript in your init script, in which case you need to use the `lua` primitive to execute Lua code, the snippet you provided is valid and perfectly fine.
