### ISSUE TITLE
Allow installation of an lsp using a forked repository

### ISSUE THREAD

**Issue by LeviticusNelson** [williamboman/mason.nvim#850]
### I've searched open issues for similar requests

Yes

### Is your feature request related to a problem? Please describe.

I am currently waiting for a PR to be merged for an lsp, and I was wondering if you can make it to where you can install a forked repository of an lsp in the meantime.

### Describe the solution you'd like

When using the cmd line:
```
:MasonInstall spectral-language-server {insert git repo url}
```

**Comment by williamboman** [comment]
Hey! This won't be implemented due to the various kinds of sources that packages use. A git repo URL would mean nothing to say an `npm` package for example. Standardizing this mechanism would require quite a lot of effort with questionable benefits (I'd personally argue it'd be an anti-feature). Releasing functional software is a responsibility of upstream vendors.

Btw I noticed that the homepage URL for `spectral-language-server` was incorrect, fixed in https://github.com/williamboman/mason.nvim/commit/b94f8ff3ac911a28ec753359afdf840f29163d7c.

As a sidenote though; I am working on [migrating package definitions](https://github.com/mason-org/mason-registry) to use [purl identifiers](https://github.com/package-url/purl-spec). In theory it'd probably be pretty easy to change components of a purl, like so:

```lua
local parsed = purl.parse("pkg:github/stoplightio/vscode-spectral@v1.1.0")
parsed.namespace = "<github-user>"
parsed.version = "<some-git-ref>"
print(parsed)
-- {
--  name = "vscode-spectral",
--  namespace = "<github-user>",
--  scheme = "pkg",
--  type = "github",
--  version = "<some-git-ref>"
-- }
```

It's definitely not a planned feature, just saying it'd probably be easy to hack with purls in place.
